const IMAGE_BASE = "https://images.unsplash.com";

function image(photoId) {
  return `${IMAGE_BASE}/photo-${photoId}?fit=crop&w=1600&h=900&q=82&fm=jpg`;
}

const EVENT_DEFINITIONS = [
  {
    title: "Noche Prisma",
    shortDescription: "Una noche de electrónica, visuales inmersivas y pista abierta hasta el amanecer.",
    longDescription: "Noche Prisma reúne productores de la escena electrónica nacional en un montaje audiovisual de gran formato. La programación recorre house, melodic techno y progressive, con apertura de puertas temprana y espacios de descanso.",
    daysFromNow: 35,
    startTime: "23:00",
    openingTime: "21:30",
    endingTime: "05:30",
    venueName: "Arena del Río",
    venueAddress: "Av. Costanera 2450",
    venuePostalCode: "C1428",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Buenos Aires",
    capacity: 5200,
    maxTicketsPerUser: 6,
    serviceFeePercent: 10,
    coverReference: image("1501386761578-eac5c94b800a"),
    ticketTypes: [
      ["General", 28000, 3000, "Acceso general a pista."],
      ["Campo preferencial", 44000, 1500, "Sector cercano al escenario."],
      ["Experiencia VIP", 72000, 700, "Ingreso prioritario y sector elevado."],
    ],
  },
  {
    title: "Horizonte Indie",
    shortDescription: "Guitarras, canciones nuevas y tres proyectos emergentes en una misma fecha.",
    longDescription: "Horizonte Indie presenta una selección de bandas de distintos puntos del país. Una fecha pensada para descubrir repertorios nuevos, con sonido en vivo, feria gráfica y propuestas gastronómicas.",
    daysFromNow: 49,
    startTime: "20:30",
    openingTime: "19:00",
    endingTime: "01:00",
    venueName: "Galpón Central",
    venueAddress: "Bv. Los Andes 860",
    venuePostalCode: "X5000",
    venueCity: "Córdoba",
    venueProvince: "Córdoba",
    capacity: 4200,
    maxTicketsPerUser: 8,
    serviceFeePercent: 9,
    coverReference: image("1492684223066-81342ee5ff30"),
    ticketTypes: [
      ["General", 24000, 2500, "Acceso al predio y escenarios."],
      ["Platea", 36000, 1200, "Ubicación numerada en platea."],
      ["Backstage experience", 68000, 500, "Sector exclusivo y acceso anticipado."],
    ],
  },
  {
    title: "Frecuencia Urbana",
    shortDescription: "Rap, freestyle y nuevos sonidos urbanos frente al río Paraná.",
    longDescription: "Frecuencia Urbana combina shows en vivo, batallas de freestyle y sesiones de DJ. Una producción compacta con artistas emergentes, intervenciones visuales y un cierre colaborativo.",
    daysFromNow: 63,
    startTime: "21:00",
    openingTime: "19:30",
    endingTime: "02:00",
    venueName: "Distrito Ribera",
    venueAddress: "Av. de los Inmigrantes 410",
    venuePostalCode: "S2000",
    venueCity: "Rosario",
    venueProvince: "Santa Fe",
    capacity: 1800,
    maxTicketsPerUser: 6,
    serviceFeePercent: 11,
    coverReference: image("1516450360452-9312f5e86fc7"),
    ticketTypes: [
      ["General", 22000, 1200, "Acceso general de pie."],
      ["Preferencial", 35000, 450, "Sector frontal con ingreso prioritario."],
      ["Meet & greet TEST", 59000, 150, "Acceso previo y fotografía grupal de prueba."],
    ],
  },
  {
    title: "Aurora Sinfónica",
    shortDescription: "Una experiencia orquestal contemporánea con repertorio de cine y música popular.",
    longDescription: "Aurora Sinfónica propone un recorrido por piezas reconocibles y arreglos originales para gran ensamble. El concierto suma diseño lumínico, visuales y una puesta íntima aun dentro de una sala de gran escala.",
    daysFromNow: 78,
    startTime: "20:00",
    openingTime: "18:45",
    endingTime: "22:30",
    venueName: "Auditorio del Parque",
    venueAddress: "Av. Sarmiento 1250",
    venuePostalCode: "M5500",
    venueCity: "Mendoza",
    venueProvince: "Mendoza",
    capacity: 1200,
    maxTicketsPerUser: 6,
    serviceFeePercent: 8,
    coverReference: image("1524368535928-5b5e00ddc76b"),
    ticketTypes: [
      ["Pullman", 26000, 500, "Ubicación numerada en nivel superior."],
      ["Platea", 39000, 500, "Ubicación numerada en platea central."],
      ["Palco", 58000, 200, "Palco lateral con vista elevada."],
    ],
  },
  {
    title: "Ruta del Blues",
    shortDescription: "Una velada de blues eléctrico, soul y canciones de carretera.",
    longDescription: "Ruta del Blues reúne una banda estable y artistas invitados en un repertorio que viaja desde el delta blues hasta el soul contemporáneo. Habrá mesas, pista y servicio gastronómico durante el show.",
    daysFromNow: 91,
    startTime: "21:30",
    openingTime: "20:00",
    endingTime: "00:30",
    venueName: "Club del Puerto",
    venueAddress: "12 de Octubre 455",
    venuePostalCode: "B7600",
    venueCity: "Mar del Plata",
    venueProvince: "Buenos Aires",
    capacity: 650,
    maxTicketsPerUser: 8,
    serviceFeePercent: 12,
    coverReference: image("1540039155733-5bb30b53aa14"),
    ticketTypes: [
      ["General", 18000, 450, "Acceso de pie y barra general."],
      ["Mesa compartida", 29000, 160, "Lugar en mesa compartida."],
      ["Mesa premium", 46000, 40, "Ubicación preferencial y recepción."],
    ],
  },
  {
    title: "La Última Función",
    shortDescription: "Un thriller teatral sobre memoria, escena y una compañía que se niega a despedirse.",
    longDescription: "Durante el ensayo final de una obra inconclusa, una compañía descubre que cada versión altera los recuerdos de sus integrantes. La Última Función combina actuación, música original y recursos cinematográficos.",
    daysFromNow: 106,
    startTime: "20:30",
    openingTime: "19:30",
    endingTime: "22:20",
    venueName: "Teatro del Pasaje",
    venueAddress: "San Martín 780",
    venuePostalCode: "T4000",
    venueCity: "San Miguel de Tucumán",
    venueProvince: "Tucumán",
    capacity: 900,
    maxTicketsPerUser: 6,
    serviceFeePercent: 10,
    coverReference: image("1503095396549-807759245b35"),
    ticketTypes: [
      ["Platea", 24000, 500, "Butaca numerada en platea."],
      ["Pullman", 19000, 300, "Butaca numerada en nivel superior."],
      ["Palco", 36000, 100, "Ubicación en palco lateral."],
    ],
  },
  {
    title: "Bajo el Mismo Techo",
    shortDescription: "Una comedia dramática sobre una familia que vuelve a reunirse después de diez años.",
    longDescription: "Una casa a punto de venderse reúne a tres hermanos con versiones incompatibles del pasado. Entre cajas, discusiones y secretos, la familia tiene una noche para decidir qué conservar.",
    daysFromNow: 120,
    startTime: "21:00",
    openingTime: "20:00",
    endingTime: "22:40",
    venueName: "Sala Norte",
    venueAddress: "Belgrano 1265",
    venuePostalCode: "A4400",
    venueCity: "Salta",
    venueProvince: "Salta",
    capacity: 480,
    maxTicketsPerUser: 6,
    serviceFeePercent: 7,
    coverReference: image("1507676184212-d03ab07a01bf"),
    ticketTypes: [
      ["General", 17000, 320, "Ubicación por orden de llegada."],
      ["Preferencial", 26000, 160, "Sector central reservado."],
    ],
  },
  {
    title: "Micrófono Abierto",
    shortDescription: "Cinco comediantes, material nuevo y una noche donde puede pasar cualquier cosa.",
    longDescription: "Micrófono Abierto es una fecha de stand-up con sets breves, anfitrión y cierre extendido. El contenido cambia en cada función y combina artistas con experiencia y nuevas voces del circuito.",
    daysFromNow: 134,
    startTime: "22:00",
    openingTime: "20:45",
    endingTime: "00:10",
    venueName: "Usina Cultural",
    venueAddress: "Mitre 980",
    venuePostalCode: "J4600",
    venueCity: "San Salvador de Jujuy",
    venueProvince: "Jujuy",
    capacity: 650,
    maxTicketsPerUser: 8,
    serviceFeePercent: 10,
    coverReference: image("1585699324551-f6c309eedeca"),
    ticketTypes: [
      ["General", 15000, 500, "Acceso general sin numerar."],
      ["Primera fila", 23000, 150, "Sector frontal reservado."],
    ],
  },
  {
    title: "Sin Filtro",
    shortDescription: "Stand-up directo, observaciones incómodas y una hora sin pausas.",
    longDescription: "Sin Filtro convierte situaciones cotidianas en un monólogo ágil con interacción moderada con el público. La función incluye artista invitado y un bloque final de material inédito.",
    daysFromNow: 148,
    startTime: "21:30",
    openingTime: "20:30",
    endingTime: "23:20",
    venueName: "Teatro Estación",
    venueAddress: "España 640",
    venuePostalCode: "R8400",
    venueCity: "San Carlos de Bariloche",
    venueProvince: "Río Negro",
    capacity: 720,
    maxTicketsPerUser: 6,
    serviceFeePercent: 9,
    coverReference: image("1524178232363-1fb2b075b655"),
    ticketTypes: [
      ["General", 19000, 500, "Butaca sin numerar."],
      ["Platea preferencial", 28000, 170, "Butaca en sector central."],
      ["Experiencia backstage TEST", 45000, 50, "Saludo posterior de prueba."],
    ],
  },
  {
    title: "Historias de Oficina",
    shortDescription: "Una comedia coral sobre reuniones eternas, chats cruzados y planes que nunca salen.",
    longDescription: "Seis personas quedan encerradas durante la presentación más importante de la empresa. Historias de Oficina mezcla comedia física, diálogos rápidos y música para retratar el caos de trabajar en equipo.",
    daysFromNow: 162,
    startTime: "20:30",
    openingTime: "19:30",
    endingTime: "22:15",
    venueName: "Espacio Andén",
    venueAddress: "Rivadavia 1320",
    venuePostalCode: "B8000",
    venueCity: "Bahía Blanca",
    venueProvince: "Buenos Aires",
    capacity: 560,
    maxTicketsPerUser: 8,
    serviceFeePercent: 8,
    coverReference: image("1514306191717-452ec28c7814"),
    ticketTypes: [
      ["General", 16500, 400, "Ubicación libre."],
      ["Preferencial", 24500, 160, "Sector central reservado."],
    ],
  },
  {
    title: "Cuerpos de Luz",
    shortDescription: "Danza contemporánea, proyecciones y música electrónica en vivo.",
    longDescription: "Cuerpos de Luz investiga el movimiento dentro de un espacio atravesado por proyecciones y sensores. Ocho intérpretes construyen una pieza en la que sonido, imagen y coreografía reaccionan en tiempo real.",
    daysFromNow: 179,
    startTime: "20:00",
    openingTime: "19:00",
    endingTime: "21:40",
    venueName: "Centro de Artes del Litoral",
    venueAddress: "Costanera Este 315",
    venuePostalCode: "N3300",
    venueCity: "Posadas",
    venueProvince: "Misiones",
    capacity: 1100,
    maxTicketsPerUser: 6,
    serviceFeePercent: 10,
    coverReference: image("1508700115892-45ecd05ae2ad"),
    ticketTypes: [
      ["General", 21000, 700, "Acceso a platea lateral."],
      ["Platea central", 32000, 300, "Butaca numerada central."],
      ["Fila escenario", 47000, 100, "Primeras filas numeradas."],
    ],
  },
  {
    title: "Raíz Flamenca",
    shortDescription: "Baile, guitarra y cante en una puesta contemporánea de raíz andaluza.",
    longDescription: "Raíz Flamenca propone un diálogo entre formas tradicionales y arreglos actuales. El espectáculo reúne seis bailaores, guitarra, percusión y cante en vivo en una puesta de gran intensidad visual.",
    daysFromNow: 197,
    startTime: "21:00",
    openingTime: "20:00",
    endingTime: "22:50",
    venueName: "Teatro de la Alameda",
    venueAddress: "Alberdi 540",
    venuePostalCode: "K4700",
    venueCity: "San Fernando del Valle de Catamarca",
    venueProvince: "Catamarca",
    capacity: 780,
    maxTicketsPerUser: 6,
    serviceFeePercent: 9,
    coverReference: image("1518834107812-67b0b7c58434"),
    ticketTypes: [
      ["General", 22000, 500, "Butaca numerada."],
      ["Platea preferencial", 34000, 220, "Sector frontal central."],
      ["Palco", 48000, 60, "Palco lateral para la función."],
    ],
  },
  {
    title: "Festival Río Adentro",
    shortDescription: "Dos escenarios, bandas en vivo y una jornada completa al aire libre.",
    longDescription: "Festival Río Adentro reúne música, gastronomía y diseño independiente en un predio abierto. La programación alterna rock, pop y electrónica, con espacios de descanso y propuestas para recorrer durante toda la jornada.",
    daysFromNow: 224,
    startTime: "16:00",
    openingTime: "14:30",
    endingTime: "02:30",
    venueName: "Parque de la Costa Sur",
    venueAddress: "Camino del Puerto 5000",
    venuePostalCode: "E3100",
    venueCity: "Paraná",
    venueProvince: "Entre Ríos",
    capacity: 12000,
    maxTicketsPerUser: 8,
    serviceFeePercent: 12,
    coverReference: image("1533174072545-7a4b6ad7a6c3"),
    ticketTypes: [
      ["General", 32000, 7000, "Acceso a los dos escenarios."],
      ["Campo preferencial", 48000, 3000, "Sector delantero en escenario principal."],
      ["Terraza", 69000, 1500, "Sector elevado con servicios exclusivos."],
      ["Full experience", 98000, 500, "Ingreso prioritario y terraza premium."],
    ],
  },
  {
    title: "Pequeños Exploradores",
    shortDescription: "Música, ciencia y aventura en un espectáculo participativo para toda la familia.",
    longDescription: "Pequeños Exploradores transforma el teatro en un laboratorio de historias. Canciones originales, experimentos visuales y personajes invitan a niñas, niños y adultos a resolver una misión colectiva.",
    daysFromNow: 251,
    startTime: "17:00",
    openingTime: "16:00",
    endingTime: "18:25",
    venueName: "Auditorio Patagonia",
    venueAddress: "Lago Argentino 220",
    venuePostalCode: "Q8300",
    venueCity: "Neuquén",
    venueProvince: "Neuquén",
    capacity: 1400,
    maxTicketsPerUser: 10,
    serviceFeePercent: 6,
    coverReference: image("1488841714725-bb4c32d1ac94"),
    ticketTypes: [
      ["Adultos", 18000, 700, "Entrada general para mayores de 12 años."],
      ["Infancias", 12000, 500, "Entrada para niñas y niños de 3 a 12 años."],
      ["Platea cercana", 24000, 200, "Ubicación numerada cercana al escenario."],
    ],
  },
  {
    title: "Circo de Medianoche",
    shortDescription: "Acrobacia, música en vivo y una puesta nocturna para imaginar lo imposible.",
    longDescription: "Circo de Medianoche combina técnicas aéreas, equilibrio, humor y una banda en escena. La propuesta utiliza iluminación teatral y una escenografía móvil para construir un viaje sin animales y apto para público general.",
    daysFromNow: 286,
    startTime: "20:30",
    openingTime: "19:15",
    endingTime: "22:30",
    venueName: "Gran Carpa del Oeste",
    venueAddress: "Acceso Oeste 8750",
    venuePostalCode: "B1708",
    venueCity: "Morón",
    venueProvince: "Buenos Aires",
    capacity: 1600,
    maxTicketsPerUser: 8,
    serviceFeePercent: 10,
    coverReference: image("1529139574466-a303027c1d8b"),
    ticketTypes: [
      ["General", 23000, 1000, "Grada lateral sin numerar."],
      ["Preferencial", 35000, 450, "Sector central numerado."],
      ["Palco familiar", 52000, 150, "Ubicación elevada con ingreso prioritario."],
    ],
  },
];

const REAL_EVENT_OVERRIDES = [
  {
    title: "Ambkor",
    shortDescription: "Ambkor en vivo en Niceto Club, Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Ambkor en Niceto Club. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-10-04T00:00:00.000Z",
    openingTime: "19:30",
    endingTime: "23:30",
    venueName: "Niceto Club",
    venueAddress: "Niceto Vega 5510",
    venuePostalCode: "C1414",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/03/banner-web-ambrok.jpg",
  },
  {
    title: "Walls",
    shortDescription: "Walls en vivo en Niceto Club, Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Walls en Niceto Club. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-10-11T00:00:00.000Z",
    openingTime: "19:30",
    endingTime: "23:30",
    venueName: "Niceto Club",
    venueAddress: "Niceto Vega 5510",
    venuePostalCode: "C1414",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/07/banner-web-walls.jpg",
  },
  {
    title: "Bebe",
    shortDescription: "Bebe en vivo en el Teatro Ópera de Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Bebe en el Teatro Ópera. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-10-16T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:00",
    venueName: "Teatro Ópera",
    venueAddress: "Av. Corrientes 860",
    venuePostalCode: "C1043",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/07/web-1100x400-BEBE.jpg",
  },
  {
    title: "Camila",
    shortDescription: "Camila en vivo en Movistar Arena, Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Camila en Movistar Arena. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-10-16T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:00",
    venueName: "Movistar Arena",
    venueAddress: "Humboldt 450",
    venuePostalCode: "C1414",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/08/banner-camila.jpg",
  },
  {
    title: "Jere Klein",
    shortDescription: "Jere Klein en vivo en el Teatro Ópera de Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Jere Klein en el Teatro Ópera. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-10-22T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:00",
    venueName: "Teatro Ópera",
    venueAddress: "Av. Corrientes 860",
    venuePostalCode: "C1043",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/06/benner-web-jk.jpg",
  },
  {
    title: "Roze",
    shortDescription: "Roze en vivo en el Teatro Ópera de Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Roze en el Teatro Ópera. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-10-25T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:00",
    venueName: "Teatro Ópera",
    venueAddress: "Av. Corrientes 860",
    venuePostalCode: "C1043",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2025/12/roze-web.jpg",
  },
  {
    title: "Jesse & Joy",
    shortDescription: "Jesse & Joy en vivo en Movistar Arena, Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Jesse & Joy en Movistar Arena. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-11-02T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:00",
    venueName: "Movistar Arena",
    venueAddress: "Humboldt 450",
    venuePostalCode: "C1414",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/03/BANNER-WEB-LEB-JJ.jpg",
  },
  {
    title: "Sergio Dalma",
    shortDescription: "Sergio Dalma en vivo en el Teatro Gran Rex de Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Sergio Dalma en el Teatro Gran Rex. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-11-04T23:30:00.000Z",
    openingTime: "19:30",
    endingTime: "23:00",
    venueName: "Teatro Gran Rex",
    venueAddress: "Av. Corrientes 857",
    venuePostalCode: "C1043",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/06/banner-web.jpg",
  },
  {
    title: "Alex Ubago",
    shortDescription: "Alex Ubago en vivo en el Teatro Gran Rex de Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Alex Ubago en el Teatro Gran Rex. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-11-08T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:00",
    venueName: "Teatro Gran Rex",
    venueAddress: "Av. Corrientes 857",
    venuePostalCode: "C1043",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2025/12/banner-web.jpg",
  },
  {
    title: "Ultraligera",
    shortDescription: "Ultraligera en vivo en Niceto Club, Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Ultraligera en Niceto Club. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-11-16T00:00:00.000Z",
    openingTime: "19:30",
    endingTime: "23:30",
    venueName: "Niceto Club",
    venueAddress: "Niceto Vega 5510",
    venuePostalCode: "C1414",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/08/banner-web-ultra-ligera.jpg",
  },
  {
    title: "Coti",
    shortDescription: "Coti en vivo en C Art Media, Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Coti en C Art Media. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-11-20T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:30",
    venueName: "C Art Media",
    venueAddress: "Av. Corrientes 6271",
    venuePostalCode: "C1427",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/05/Mesa-de-trabajo-3.jpg",
  },
  {
    title: "XLOV",
    shortDescription: "XLOV en vivo en C Art Media, Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de XLOV en C Art Media. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-11-26T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:30",
    venueName: "C Art Media",
    venueAddress: "Av. Corrientes 6271",
    venuePostalCode: "C1427",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/08/banner-XLOV.jpg",
  },
  {
    title: "Gabriel Rolón",
    shortDescription: "Gabriel Rolón en Movistar Arena, Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Gabriel Rolón en Movistar Arena. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2026-12-12T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:00",
    venueName: "Movistar Arena",
    venueAddress: "Humboldt 450",
    venuePostalCode: "C1414",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/07/banner-webrolon.jpg",
  },
  {
    title: "Geoff Tate — Operation: Mindcrime",
    shortDescription: "Geoff Tate presenta Operation: Mindcrime en el Teatro Vorterix.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Geoff Tate en el Teatro Vorterix. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2027-01-15T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:30",
    venueName: "Teatro Vorterix",
    venueAddress: "Federico Lacroze 3455",
    venuePostalCode: "C1426",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/07/GEOFF-TATE-banner.jpg",
  },
  {
    title: "Reik",
    shortDescription: "Reik en vivo en Movistar Arena, Buenos Aires.",
    longDescription: "Evento de prueba de BlackNight basado en la fecha oficial de Reik en Movistar Arena. Esta publicación se utiliza para validar el circuito de compra TEST y no constituye una entrada oficial del espectáculo.",
    startAt: "2027-02-15T00:00:00.000Z",
    openingTime: "19:00",
    endingTime: "23:00",
    venueName: "Movistar Arena",
    venueAddress: "Humboldt 450",
    venuePostalCode: "C1414",
    venueCity: "Ciudad Autónoma de Buenos Aires",
    venueProvince: "Ciudad Autónoma de Buenos Aires",
    coverReference: "https://leb-ent.com/wp-content/uploads/2026/06/BANNER-WEB-REIKarg.jpg",
  },
];

function futureIso(anchor, daysFromNow, localTime) {
  const [hour, minute] = localTime.split(":").map(Number);
  const date = new Date(anchor);
  date.setUTCHours(12, 0, 0, 0);
  date.setUTCDate(date.getUTCDate() + daysFromNow);
  date.setUTCHours(hour + 3, minute, 0, 0);
  return date.toISOString();
}

export function buildCatalog(batchId, anchor = new Date()) {
  const batchTag = `[BLACKNIGHT_TEST_BATCH:${batchId}]`;

  return EVENT_DEFINITIONS.map((baseDefinition, index) => {
    const definition = { ...baseDefinition, ...REAL_EVENT_OVERRIDES[index] };
    return ({
    code: `EVENT_${String(index + 1).padStart(3, "0")}`,
    coverReference: definition.coverReference,
    payload: {
      title: definition.title,
      shortDescription: definition.shortDescription,
      longDescription: `${definition.longDescription}\n\n${batchTag} [BLACKNIGHT_TEST_EVENT:${String(index + 1).padStart(3, "0")}]`,
      startAt: definition.startAt || futureIso(anchor, definition.daysFromNow, definition.startTime),
      capacity: definition.capacity,
      maxTicketsPerUser: definition.maxTicketsPerUser,
      serviceFeePercent: definition.serviceFeePercent,
      openingTime: definition.openingTime,
      endingTime: definition.endingTime,
      venueName: definition.venueName,
      venueAddress: definition.venueAddress,
      venuePostalCode: definition.venuePostalCode,
      venueCity: definition.venueCity,
      venueProvince: definition.venueProvince,
      venueCountry: "Argentina",
      ticketTypes: definition.ticketTypes.map(([name, price, stock, description], order) => ({
        name,
        price,
        stock,
        description,
        color: ["#7C3AED", "#A855F7", "#D946EF", "#F59E0B"][order],
        active: true,
        order: order + 1,
      })),
    },
    });
  });
}
